# Generated by Django 3.1.2 on 2020-11-05 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snacks')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('category', models.ManyToManyField(to='calories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('first_name', models.CharField(default='collins', max_length=20)),
                ('last_name', models.CharField(default='akumu', max_length=20)),
                ('status', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=200, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default='80', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default='120', max_digits=6)),
                ('birth_field', models.DateField(default='2005-12-24')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFooditem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fooditem', models.ManyToManyField(to='calories.Fooditem')),
                ('profile', models.ManyToManyField(blank=True, related_name='user_diet', to='calories.Profile')),
            ],
        ),
    ]
